= Migrate from OpenWire protocol

OpenWire is a legacy ActiveMQ wire protocol which is now deprecated in Red Hat AMQ 7 (ActiveMQ Artemis). Migrating the existing client applications to an alternative protocol requires code changes are regression testing.

The Openwire client jar file has a name like `activemq-client.jar`, or in maven _pom.xml_ look for `<groupId>org.apache.activemq</groupId> <artifactId>activemq-client</artifactId>`.

== Protocols

Pick one of the alternative protocols supported by Artemis message broker:

* link:core[CORE]
* link:amqp[AMQP]

Quick pick:

* JBoss EAP apps -> CORE is built-in, but can use AMQP too
* Java apps with XA transactions -> use CORE
* Wants to use automatic broker failover feature -> use AMQP
* .NET apps -> use AMQP
* Prefer AMQP over CORE because that's a standard protocol

== Clients

Documentation: https://access.redhat.com/documentation/en-us/red_hat_amq_clients/2.11

Downloads: https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.clients

== Virtual Topics

Virtual Topics is an Openwire specific feature and it's not trivial how to use similar queue structure with other protocols.

* link:virtualtopics[Virtual Topics]