= AMQP protocol

AMQ Broker uses AMQP 1.0 (which is not compatible with AMQP v0.9.1).

*Pros*

* AMQP is a messaging standard
* Clients exist for multiple languages, see https://qpid.apache.org/index.html[Apache Qpid]

*Cons*

* XA transactions are not supported

*Notes*

* AMQP protocol traditionally uses port `5672` for non-TLS and `5671` for TLS secured connections
* With AMQ Broker we usually simply use port `61617` with TLS enabled
* It's possible to use AMQP in an app deployed on JBoss EAP as a custom jar added to the war

== Clients

AMQP clients:

* AMQ Clients JMS (Qpid JMS)
* AMQ .NET Client (AMQP.Net Lite)
* Qpid Proton DotNet (recommended)
* AMQ Clients Python 3.x (Qpid Proton)
* AMQ Clients C++ (Qpid Proton)
* AMQ JavaScript Client (Rhea)
* AMQ Ruby Client (Qpid Proton)

== Java client

https://qpid.apache.org/components/jms/index.html[Qpid JMS client] has two builds. Pick the build based on the framework and other libraries you use in your app:

* JMS 2 API (javax.jms): version 1.x
* Jakarta API (jakarta.jms): version 2.x

Jakarta API is used starting these version:

* SpringBoot 3
* Spring Framework 6
* Quarkus 3
* JBoss EAP 8
* Apache Camel 4

=== Red Hat builds

Doc: https://access.redhat.com/documentation/en-us/red_hat_amq_clients/2.11/html-single/using_the_amq_jms_client/index
Maven: https://maven.repository.redhat.com/earlyaccess/all/org/apache/qpid/qpid-jms-client/

* Currently v1.x (javax.jms) builds are available
* Last build for Java8 is `0.61.0.redhat-00001`, newer versions require Java11

To use the Red Hat build of the JMS client add dependency to _pom.xml_:

[source,xml]
```
<dependency>
    <groupId>org.apache.qpid</groupId>
    <artifactId>qpid-jms-client</artifactId>
    <version>1.7.0.redhat-00002</version>
</dependency>
```

Also make sure that _JMS 2.0_ API spec is used as dependency (instead of _JMS 1.1_):

```
<dependency>
    <groupId>org.apache.geronimo.specs</groupId>
    <artifactId>geronimo-jms_2.0_spec</artifactId>
    <version>1.0.0.alpha-2-redhat-2</version>
</dependency>
```

=== Code

The AMQP client supports JMS2 API, which is backward compatible with JMS1.1. Create `ConnectionFactory` as:

```
javax.jms.ConnectionFactory connFactory = new org.apache.qpid.jms.JmsConnectionFactory(brokerUrl);
```

== URL

AMQP protocol requires a different broker URL than Openwire. See URL format and https://qpid.apache.org/releases/qpid-jms-1.8.0/docs/index.html#jms-configuration-options[parameters]. Examples:

* Simple non-TLS
+
`amqp://host:5672`

* TLS enabled server - trust every certificate
+
`amqps://host:61617?transport.verifyHost=false&transport.trustAll=true`

* TLS enabled server - truststores
+
`amqps://host:61617?transport.trustStoreLocation=./client.ts&transport.trustStorePassword=changeit`

* Prefetch size
+
`amqp://localhost:5672?jms.prefetchPolicy.all=10`

* Failover - OpenShift Routes
+
`failover:(amqps://route-0.apps.mycluster.mycompany.com:443,amqps://route-1.apps.mycluster.mycompany.com:443)?failover.maxReconnectAttempts=15&failover.amqpOpenServerListAction=IGNORE`




